#!/bin/bash

#1 se config kullanici sifresini atar yoksa config kullanici sifresi olusturmaz
UPDATE_CONFIG_USER=1
CNCONFIGADMINDN="cn=admin,cn=config"
CNCONFIGADMINPASSWD="secret"
BASE_DN="dc=liderahenk,dc=org,dc=tr"
LIDERAHENK_SCHEMA_PATH="/tmp/liderahenk.ldif"
LDAP_DATABASE_ADMIN_DN="cn=admin,dc=liderahenk,dc=org,dc=tr"
LDAP_DATABASE_ADMIN_PASSWORD="1"
LIDER_SERVER_ADDR="http://192.140.98.226"
LADMIN_PASSWORD="1"

if [ $UPDATE_CONFIG_USER -eq 1 ]; then
  #Varsayilan sifre secret
NEW_PASSWD=$(slappasswd -h {SSHA} -s $CNCONFIGADMINPASSWD)

#mevcut cn=config sifresini siler ve yenisini ekler
ldapmodify -Y EXTERNAL -H ldapi:/// << EOL
dn: olcDatabase={0}config,cn=config
replace: olcRootPW
olcRootPW: $NEW_PASSWD

dn: cn=config
replace: olcAuthzRegexp
olcAuthzRegexp: {0}uid=([^,]*),cn=[^,]*,cn=auth  ldap:///$BASE_DN??sub?(uid=\$1)
-
replace: olcSizeLimit
olcSizeLimit: 10000
EOL

fi


# Install liderahenk schema ldif
ldapadd -x -f $LIDERAHENK_SCHEMA_PATH -D "$CNCONFIGADMINDN" -w $CNCONFIGADMINPASSWD

service slapd restart

ldapadd -x -D "$LDAP_DATABASE_ADMIN_DN" -w $LDAP_DATABASE_ADMIN_PASSWORD << EOL

dn: ou=Uncategorized,$BASE_DN
objectClass: top
objectClass: organizationalUnit
ou: Uncategorized
EOL

ldapadd -x -D "$LDAP_DATABASE_ADMIN_DN" -w $LDAP_DATABASE_ADMIN_PASSWORD << EOL

dn: cn=liderAhenkConfig,$BASE_DN
objectClass: pardusLiderAhenkConfig
cn: liderAhenkConfig
liderServiceAddress: $LIDER_SERVER_ADDR
EOL

ldapadd -x -D "$LDAP_DATABASE_ADMIN_DN" -w $LDAP_DATABASE_ADMIN_PASSWORD << EOL

dn: cn=ladmin,$BASE_DN
objectClass: pardusLider
objectClass: pardusAccount
objectClass: top
objectClass: person
objectClass: organizationalPerson
objectClass: inetOrgPerson
cn: ladmin
sn: ladmin
uid: ladmin
userPassword: $LADMIN_PASSWORD
liderPrivilege: [$BASE_DN:ALL:true]
EOL

service slapd restart

#bitti
exit 0
